# Generated by Django 5.2.3 on 2025-06-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assignment_attendance_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostAndFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('found_location', models.CharField(max_length=255)),
                ('retrieving_place', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
