# Generated by Django 5.2.3 on 2025-06-24 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lostandfound'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vote')),
            ],
        ),
    ]
