# Generated by Django 5.2.3 on 2025-06-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteresult',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
    ]
