from django.urls import path
from . import views

urlpatterns = [
    path('register/student/', views.register_student),
    path('register/teacher/', views.register_teacher),
    path('login/', views.login_user),
    path('add-course/', views.add_course),
    path('get-course/', views.get_course),
    path('add-vote/', views.add_vote),
    path('get-vote/', views.get_vote),
    path('add-notice/', views.add_notice),
    path('get-notice/', views.get_notice),
    path('students/', views.get_students),
    path('teachers/', views.get_teachers),
    path('delete-student/<int:student_id>/', views.delete_student),
    path('delete-teacher/<int:teacher_id>/', views.delete_teacher),
    path('profile/<str:role>/<str:user_id>/', views.get_user_profile),
    path('upload-chapter/', views.upload_chapter),
    path('upload-assignment/', views.upload_assignment),
    path('attendance/<int:course_id>/', views.attendance_search),
    path('get-course-with-content/', views.get_courses_with_content),
    path('delete-chapter/<int:chapter_id>/', views.delete_chapter),
    path('delete-assignment/<int:assignment_id>/', views.delete_assignment),
    path('lost-found-items/', views.get_lost_items),
    path('upload-lost-item/', views.upload_lost_item),
    path('delete-lost-item/<int:pk>/', views.delete_lost_item),
    path('submit-vote/', views.submit_vote),
    path('get-vote-results/', views.get_vote_results),
    path('take-attendance/', views.take_attendance),
    path('submit-assignment/', views.submit_assignment),
    path('search-submissions/', views.search_student_submissions),
    path('get-submissions/', views.get_submissions),
    path('verify-key/', views.verify_attendance_key),
]
